version: '3.7'
services:
  client:
    build:
      context: './client'
      dockerfile: Dockerfile
    image: client
    ports:
      - "3000:3000"
  server:
    build:
      context: './server'
      dockerfile: Dockerfile
    image: server
    ports:
      - "8080:8080"